repos:
    - repo: https://github.com/pycqa/isort
      rev: '5.10.1'
      hooks:
        - id: isort
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
        - id: check-added-large-files
    - repo: https://github.com/pycqa/flake8
      rev: '4.0.1'
      hooks:
        - id: flake8
    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v1.6.0
      hooks:
        - id: autopep8
